### ISSUE TITLE
cgo-gcc linke-issue 

### ISSUE THREAD

**Issue by bendney** [jprjr/rtmp-janus#1]
# command-line-arguments
/tmp/go-build151217969/b001/_x002.o: In function `_cgo_658371149a58_Cfunc_aac_decoder_decode':
/tmp/go-build/cgo-gcc-prolog:66: undefined reference to `aac_decoder_decode'
/tmp/go-build151217969/b001/_x002.o: In function `_cgo_658371149a58_Cfunc_aac_decoder_new':
/tmp/go-build/cgo-gcc-prolog:83: undefined reference to `aac_decoder_new'
/tmp/go-build151217969/b001/_x002.o: In function `_cgo_658371149a58_Cfunc_aac_decoder_open':
/tmp/go-build/cgo-gcc-prolog:104: undefined reference to `aac_decoder_open'
/tmp/go-build151217969/b001/_x002.o: In function `_cgo_658371149a58_Cfunc_audio_fifo_load':
/tmp/go-build/cgo-gcc-prolog:136: undefined reference to `audio_fifo_load'
/tmp/go-build151217969/b001/_x002.o: In function `_cgo_658371149a58_Cfunc_audio_fifo_new':
/tmp/go-build/cgo-gcc-prolog:155: undefined reference to `audio_fifo_new'
/tmp/go-build151217969/b001/_x002.o: In function `_cgo_658371149a58_Cfunc_audio_fifo_open':
/tmp/go-build/cgo-gcc-prolog:176: undefined reference to `audio_fifo_open'
/tmp/go-build151217969/b001/_x002.o: In function `_cgo_658371149a58_Cfunc_audio_fifo_read':
/tmp/go-build/cgo-gcc-prolog:196: undefined reference to `audio_fifo_read'
/tmp/go-build151217969/b001/_x002.o: In function `_cgo_658371149a58_Cfunc_audio_fifo_size':
/tmp/go-build/cgo-gcc-prolog:215: undefined reference to `audio_fifo_size'
/tmp/go-build151217969/b001/_x002.o: In function `_cgo_658371149a58_Cfunc_opus_encoder_encode':
/tmp/go-build/cgo-gcc-prolog:266: undefined reference to `opus_encoder_encode'
/tmp/go-build151217969/b001/_x002.o: In function `_cgo_658371149a58_Cfunc_opus_encoder_new':
/tmp/go-build/cgo-gcc-prolog:285: undefined reference to `opus_encoder_new'
/tmp/go-build151217969/b001/_x002.o: In function `_cgo_658371149a58_Cfunc_aac_decoder_close':
/tmp/go-build/cgo-gcc-prolog:49: undefined reference to `aac_decoder_close'
/tmp/go-build151217969/b001/_x002.o: In function `_cgo_658371149a58_Cfunc_audio_fifo_close':
/tmp/go-build/cgo-gcc-prolog:119: undefined reference to `audio_fifo_close'
/tmp/go-build151217969/b001/_x002.o: In function `_cgo_658371149a58_Cfunc_opus_encoder_close':
/tmp/go-build/cgo-gcc-prolog:250: undefined reference to `opus_encoder_close'
/tmp/go-build151217969/b001/_x003.o: In function `_cgo_658371149a58_Cfunc_aac_decoder_init':
/tmp/go-build/cgo-gcc-prolog:52: undefined reference to `aac_decoder_init'
collect2: error: ld returned 1 exit status

Could you add the build process for this project ? thanks

**Comment by jprjr** [comment]
I just type `go build` which seems to build the C code automatically.

I wrote most of this using Ubuntu 16.04 with it's default ffmpeg/libavcodec version, but did use a newer version of Go (1.14). Just tested again on arch linux, works there as well. Maybe you're mising the libavcodec/libavutil dependencies?

What do these commands show?

```
pkg-config --modversion libavcodec
pkg-config --modversion libavutil
pkg-config --modversion libswresample
```

**Comment by bendney** [comment]
I'm using centos7, built 4.2.1 ffmpeg by myself,  the output for these command is version for relevant library, I type the wrong command for buiding, now it's done. 

But there is another issue for centos7 and opus 1.3.1: opus_encoder_init confilct with opus 1.3.1  funtion, I change the function name for difference and then build successfully.  Could u change the name for compatible?

**Comment by jprjr** [comment]
Done, try now - prefixed all the local C functions/types with "rtmpjanus" in 5a7c41321f11413ce77049bfcbc8fe16d135bcdf

**Comment by bendney** [comment]
All done, thanks!
